insert into public.catalog_colors (name, hex, sort_order) values
  ('BEGE DUNAS', '#c8b89a', 10),
  ('CARVALHO JARI', '#a0784a', 20),
  ('BRANCO SNOW', '#f5f3ef', 30),
  ('CINZA SAGRADO', '#8a8a8a', 40),
  ('GRAFITE', '#4a4a4a', 50),
  ('OFF WHITE', '#f0ede6', 60),
  ('MACADAMIA', '#c4a882', 70),
  ('PRETO PIANO', '#1a1a1a', 80),
  ('NOGUEIRA', '#6b4c32', 90),
  ('AREIA', '#d4c4a8', 100)
on conflict (name) do update set
  hex = excluded.hex,
  sort_order = excluded.sort_order,
  active = true;

insert into public.catalog_options (group_key, label, sort_order) values
  ('tamponamentos', '15mm', 10),
  ('tamponamentos', '25mm', 20),
  ('tamponamentos', '15mm e 25mm', 30),
  ('tamponamentos', '6mm', 40),
  ('tamponamentos', '15mm e 6mm', 50),
  ('portas', 'LISA', 10),
  ('portas', 'CAVA 45°', 20),
  ('portas', 'PASSANTE', 30),
  ('portas', 'FRISO', 40),
  ('portas', 'ROMEU E JULIETA', 50),
  ('portas', 'AMERICANA', 60),
  ('portas', 'ESPELHO', 70),
  ('puxadores', 'CAVA 45°', 10),
  ('puxadores', 'GARD 256mm', 20),
  ('puxadores', 'PASSANTE', 30),
  ('puxadores', 'LISA PASSANTE', 40),
  ('puxadores', 'EMBUTIDO', 50),
  ('puxadores', 'PUXADOR J', 60),
  ('puxadores', 'PUXADOR L', 70),
  ('observacoes', 'Apenas Marcenaria considerado no ambiente', 10),
  ('observacoes', 'Apenas Marcenaria e serralheria considerados no ambiente', 20),
  ('observacoes', 'Leds nao inclusos', 30),
  ('observacoes', 'Considerar cavas para instalacao de LEDS', 40),
  ('observacoes', 'Eletrodomesticos nao inclusos', 50)
on conflict (group_key, label) do update set
  sort_order = excluded.sort_order,
  active = true;

insert into public.catalog_materials (group_key, name, code, brand, hex, sort_order) values
  ('madeira', 'CARVALHO JARI', 'CARVALHO-JARI', 'Dcoratto', '#a0784a', 10),
  ('madeira', 'NOGUEIRA', 'NOGUEIRA', 'Dcoratto', '#6b4c32', 20),
  ('madeira', 'BEGE DUNAS', 'BEGE-DUNAS', 'Dcoratto', '#c8b89a', 30),
  ('laca', 'GRAFITE', 'GRAFITE', 'Dcoratto', '#4a4a4a', 40),
  ('laca', 'BRANCO SNOW', 'BRANCO-SNOW', 'Dcoratto', '#f5f3ef', 50),
  ('laca', 'OFF WHITE', 'OFF-WHITE', 'Dcoratto', '#f0ede6', 60),
  ('puxador', 'CAVA 45°', 'CAVA-45', 'Dcoratto', null, 70),
  ('puxador', 'PASSANTE', 'PASSANTE', 'Dcoratto', null, 80),
  ('porta', 'LISA', 'LISA', 'Dcoratto', null, 90),
  ('porta', 'FRISO', 'FRISO', 'Dcoratto', null, 100),
  ('tamponamento', '15mm', '15MM', 'Dcoratto', null, 110),
  ('tamponamento', '25mm', '25MM', 'Dcoratto', null, 120)
on conflict (group_key, name) do update set
  code = excluded.code,
  brand = excluded.brand,
  hex = excluded.hex,
  sort_order = excluded.sort_order,
  active = true;

with boa_vista_colors(sort_order, line_name, name, quality, hex, texture_url) as (
  values
    (10, 'ARAUCO', 'Branco Supremo', 'MDP', '#d3d9d8', '/catalog/boa-vista/p02-im03.webp'),
    (20, 'ARAUCO', 'Beton Matt', 'MDP', '#aabebb', '/catalog/boa-vista/p02-im05.webp'),
    (30, 'ARAUCO', 'Beige', 'MDP', '#bdc2bb', '/catalog/boa-vista/p02-im04.webp'),
    (40, 'ARAUCO', 'Canela', 'MDP', '#81827c', '/catalog/boa-vista/p02-im01.webp'),
    (50, 'ARAUCO', 'Carvalho', 'MDP', '#bbae98', '/catalog/boa-vista/p02-im02.webp'),
    (60, 'ARAUCO', 'Grafito', 'MDP', '#5c6c6f', '/catalog/boa-vista/p02-im00.webp'),
    (70, 'ARAUCO', 'Jalapao', 'MDP', '#904a2e', '/catalog/boa-vista/p02-im07.webp'),
    (80, 'ARAUCO', 'Lord', 'MDP', '#5b6e84', '/catalog/boa-vista/p02-im08.webp'),
    (90, 'ARAUCO', 'Nogueira Pecan', 'MDP', '#605049', '/catalog/boa-vista/p02-im06.webp'),
    (100, 'BERNECK', 'Branco', 'MDF / MDP', '#e9efed', '/catalog/boa-vista/p03-im02.webp'),
    (110, 'BERNECK', 'Cinamomo', 'MDP', '#aa807a', '/catalog/boa-vista/p03-im03.webp'),
    (120, 'BERNECK', 'Louro Freijo', 'MDP', '#84725f', '/catalog/boa-vista/p03-im09.webp'),
    (130, 'BERNECK', 'Louro Preto', 'MDP', '#635b59', '/catalog/boa-vista/p03-im10.webp'),
    (140, 'BERNECK', 'Macadamia', 'MDP', '#a49788', '/catalog/boa-vista/p03-im11.webp'),
    (150, 'BERNECK', 'Millennial', 'MDP', '#b49f93', '/catalog/boa-vista/p03-im07.webp'),
    (160, 'BERNECK', 'Nude Vel', 'MDP', '#c9d2c2', '/catalog/boa-vista/p03-im08.webp'),
    (170, 'BERNECK', 'Opera Vel', 'MDP', '#97a59d', '/catalog/boa-vista/p03-im06.webp'),
    (180, 'BERNECK', 'Sky', 'MDP', '#a5cbda', '/catalog/boa-vista/p03-im04.webp'),
    (190, 'BERNECK', 'Plomo', 'MDP', '#738383', '/catalog/boa-vista/p03-im05.webp'),
    (200, 'BERNECK', 'Preto', 'MDP', '#07090d', '/catalog/boa-vista/p03-im01.webp'),
    (210, 'BERNECK', 'Verti', 'MDP', '#708976', '/catalog/boa-vista/p03-im00.webp'),
    (220, 'DURATEX', 'Absoluto', 'MDF', '#525a5c', '/catalog/boa-vista/p04-im05.webp'),
    (230, 'DURATEX', 'Branco Diamante Cristalo', 'MDF', '#d5e0de', '/catalog/boa-vista/p04-im10.webp'),
    (240, 'DURATEX', 'Cinza Sagrado', 'MDF', '#838f92', '/catalog/boa-vista/p04-im02.webp'),
    (250, 'DURATEX', 'Cinza Sagrado Essencial', 'MDP', '#9ca09e', '/catalog/boa-vista/p04-im13.webp'),
    (260, 'DURATEX', 'Gianduia', 'MDF', '#879f9e', '/catalog/boa-vista/p04-im09.webp'),
    (270, 'DURATEX', 'Gianduia Puro', 'MDP', '#8e8f80', '/catalog/boa-vista/p04-im03.webp'),
    (280, 'DURATEX', 'Lana', 'MDP', '#c1cbc8', '/catalog/boa-vista/p04-im14.webp'),
    (290, 'DURATEX', 'Mint', 'MDP', '#aac8b4', '/catalog/boa-vista/p04-im12.webp'),
    (300, 'DURATEX', 'Ocre Solar', 'MDP', '#c1ae85', '/catalog/boa-vista/p04-im11.webp'),
    (310, 'DURATEX', 'Off White', 'MDP', '#bfc3b5', '/catalog/boa-vista/p04-im04.webp'),
    (320, 'DURATEX', 'Pau Ferro Cristalo', 'MDF', '#7d534a', '/catalog/boa-vista/p04-im08.webp'),
    (330, 'DURATEX', 'Preto Acetinatto', 'MDF', '#495456', '/catalog/boa-vista/p04-im07.webp'),
    (340, 'DURATEX', 'Preto Diamante Cristalo', 'MDF', '#414548', '/catalog/boa-vista/p04-im01.webp'),
    (350, 'DURATEX', 'Titanio', 'MDF', '#c9d7bb', '/catalog/boa-vista/p04-im00.webp'),
    (360, 'DURATEX', 'Verde Floresta', 'MDP', '#687a5f', '/catalog/boa-vista/p04-im06.webp'),
    (370, 'GUARARAPES', 'Capuccino', 'MDF', '#b3aca5', '/catalog/boa-vista/p05-im04.webp'),
    (380, 'GUARARAPES', 'Curupixa', 'MDF', '#dcbba2', '/catalog/boa-vista/p05-im05.webp'),
    (390, 'GUARARAPES', 'Fontana', 'MDF', '#c1c8b9', '/catalog/boa-vista/p05-im03.webp'),
    (400, 'GUARARAPES', 'Marmo', 'MDF', '#404345', '/catalog/boa-vista/p05-im01.webp'),
    (410, 'GUARARAPES', 'Quartzo', 'MDF', '#c6d1ca', '/catalog/boa-vista/p05-im02.webp'),
    (420, 'GUARARAPES', 'Rosa Milkshake', 'MDF', '#d3bcba', '/catalog/boa-vista/p05-im00.webp'),
    (430, 'GREEN PLAC', 'Veredas', 'MDF', '#c2bba4', '/catalog/boa-vista/p05-im06.webp'),
    (440, 'LAMINAS NATURAIS', 'Carvalho Catedral', '', '#ab9d8e', '/catalog/boa-vista/p06-im01.webp'),
    (450, 'LAMINAS NATURAIS', 'Freijo Catedral', '', '#a78a70', '/catalog/boa-vista/p06-im02.webp'),
    (460, 'LAMINAS NATURAIS', 'Jequitiba Natural', '', '#a17f73', '/catalog/boa-vista/p06-im03.webp'),
    (470, 'LAMINAS NATURAIS', 'Nogueira Americana', '', '#8a746d', '/catalog/boa-vista/p06-im04.webp'),
    (480, 'LAMINAS NATURAIS', 'Pau Ferro', '', '#866a5d', '/catalog/boa-vista/p06-im00.webp')
)
insert into public.catalog_materials (
  group_key,
  name,
  code,
  brand,
  manufacturer,
  line_name,
  quality,
  hex,
  texture_url,
  sort_order,
  data
)
select
  'boa_vista_cores',
  name,
  upper(regexp_replace(line_name || '-' || name || case when quality <> '' then '-' || quality else '' end, '[^a-zA-Z0-9]+', '-', 'g')),
  'Boa Vista',
  'BOA VISTA',
  line_name,
  quality,
  hex,
  texture_url,
  sort_order,
  jsonb_build_object(
    'sourceDocument', 'CATALOGO PADROES DE CORES BOA VISTA',
    'exclusiveToManufacturer', 'BOA VISTA'
  )
from boa_vista_colors
on conflict (group_key, name) do update set
  code = excluded.code,
  brand = excluded.brand,
  manufacturer = excluded.manufacturer,
  line_name = excluded.line_name,
  quality = excluded.quality,
  hex = excluded.hex,
  texture_url = excluded.texture_url,
  sort_order = excluded.sort_order,
  data = excluded.data,
  active = true;
